#!/usr/bin/env node
/**
 * 内联脚本：把 worker/skill/ 下的 md 文件打包成 worker/skill-bundle.js。
 * 这样 wrangler 标准构建即可识别，无需 md import 插件。
 *
 * 与 sync-skill.js 配合使用：
 *   1. sync-skill.js  把 .agents 的 md 拷到 web/public/skill 和 worker/skill
 *   2. inline-skill.js 把 worker/skill 的 md 转成 worker/skill-bundle.js
 */
const fs = require('fs');
const path = require('path');

const REPO_ROOT = path.resolve(__dirname, '..');
const SKILL_DIR = path.join(REPO_ROOT, 'worker', 'skill');
const OUT_FILE = path.join(REPO_ROOT, 'worker', 'skill-bundle.js');

function read(p) {
  if (!fs.existsSync(p)) {
    console.error(`❌ 缺少: ${p}`);
    console.error('   请先运行: node scripts/sync-skill.js');
    process.exit(1);
  }
  return fs.readFileSync(p, 'utf8');
}

function main() {
  const skill = read(path.join(SKILL_DIR, 'SKILL.md'));
  const rules = read(path.join(SKILL_DIR, 'references', 'rules.md'));
  const strategy = read(path.join(SKILL_DIR, 'references', 'strategy.md'));
  const glossary = read(path.join(SKILL_DIR, 'references', 'glossary.md'));

  // 把 md 文本作为模板字符串嵌入；需要转义反引号和 ${}
  const esc = (s) => s.replace(/`/g, '\\`').replace(/\$\{/g, '\\${');

  const content = `/* AUTO-GENERATED by scripts/inline-skill.js — 不要手动编辑 */
/* eslint-disable */
export default {
  skill: \`${esc(skill)}\`,
  rules: \`${esc(rules)}\`,
  strategy: \`${esc(strategy)}\`,
  glossary: \`${esc(glossary)}\`,
};
`;

  fs.writeFileSync(OUT_FILE, content);
  console.log(`[ok] ${path.relative(REPO_ROOT, OUT_FILE)} (${(content.length / 1024).toFixed(1)} KB)`);
}

main();
